version: '3.8'

services:
  dev:
    container_name: finance-control_dev
    image: docker.io/library/finance-control:development
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn start:dev
    env_file: .env
    volumes:
      - .:/opt/finance-control
      - /opt/finance-control/node_modules
  db:
    image: postgres:alpine
    container_name: fc_pgsql
    env_file:
      - .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /opt/finance-control/docker-volumes/db/:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
  pg_admin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - '8080:80'
    depends_on:
      - db
  #redis:
  # container_name: aluraflix-redis
  #image: redis:alpine
  #command: --bind 0.0.0.0
  #ports:
  # - '6379:6379'
  #restart: always
