#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
  CREATE DATABASE 'finance-control';
  GRANT ALL PRIVILEGES ON DATABASE 'finance-control' TO $POSTGRES_USER;
EOSQL